DOWNLOAD_CACHE: /home/ubuntu/.detectron-model-cache
MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 145
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.005
  GAMMA: 0.1
  MAX_ITER: 120000
  STEPS: [0, 80000, 116000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  MULTILEVEL_ROIS: True
  #RPN_MAX_LEVEL: 7
  #RPN_MIN_LEVEL: 3
  #COARSEST_STRIDE: 128
  #EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('visualgenome', )
  SCALES: (500,)
  MAX_SIZE: 833
  RPN_STRADDLE_THRESH: -1  # default 0
  #IMS_PER_BATCH: 2
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('visualgenome',)
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: .
